version: '3'
services:
  web:
    image: python:3.11
    container_name: my-flask-app
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["python", "app.py"]
